#! /bin/bash

#---- LINUX --->

# find the full path of this script
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd "$SCRIPTPATH/src/"
gksu /usr/bin/env python "statusyzer.pyw" #gnome only
